# IPython log file

runfile('C:/Users/wzy/Desktop/MachineLearning/LinearRegression_Project2/LinearRegression.py', wdir='C:/Users/wzy/Desktop/MachineLearning/LinearRegression_Project2')
runfile('C:/Users/wzy/Desktop/MachineLearning/LinearRegression_Project3/LinearRegression.py', wdir='C:/Users/wzy/Desktop/MachineLearning/LinearRegression_Project3')
runfile('C:/Users/wzy/Desktop/MachineLearning/LinearRegression_Project3/LinearRegression.py', wdir='C:/Users/wzy/Desktop/MachineLearning/LinearRegression_Project3')
runfile('C:/Users/wzy/Desktop/MachineLearning/RidgeRegression_Project1/RidgeRegression.py', wdir='C:/Users/wzy/Desktop/MachineLearning/RidgeRegression_Project1')
debugfile('C:/Users/wzy/Desktop/MachineLearning/RidgeRegression_Project1/RidgeRegression.py', wdir='C:/Users/wzy/Desktop/MachineLearning/RidgeRegression_Project1')
runfile('C:/Users/wzy/Desktop/MachineLearning/RidgeRegression_Project1/RidgeRegression.py', wdir='C:/Users/wzy/Desktop/MachineLearning/RidgeRegression_Project1')
runfile('C:/Users/wzy/Desktop/MachineLearning/RidgeRegression_Project2/RidgeRegression.py', wdir='C:/Users/wzy/Desktop/MachineLearning/RidgeRegression_Project2')
debugfile('C:/Users/wzy/Desktop/MachineLearning/RidgeRegression_Project2/RidgeRegression.py', wdir='C:/Users/wzy/Desktop/MachineLearning/RidgeRegression_Project2')
debugfile('C:/Users/wzy/Desktop/MachineLearning/RidgeRegression_Project2/RidgeRegression.py', wdir='C:/Users/wzy/Desktop/MachineLearning/RidgeRegression_Project2')
debugfile('C:/Users/wzy/Desktop/MachineLearning/RidgeRegression_Project2/RidgeRegression.py', wdir='C:/Users/wzy/Desktop/MachineLearning/RidgeRegression_Project2')
runfile('C:/Users/wzy/Desktop/MachineLearning/LinearRegression_Project4/LinearRegression.py', wdir='C:/Users/wzy/Desktop/MachineLearning/LinearRegression_Project4')
runfile('C:/Users/wzy/Desktop/MachineLearning/LinearRegression_Project4/LinearRegression.py', wdir='C:/Users/wzy/Desktop/MachineLearning/LinearRegression_Project4')
runfile('C:/Users/wzy/Desktop/MachineLearning/LinearRegression_Project4/LinearRegression.py', wdir='C:/Users/wzy/Desktop/MachineLearning/LinearRegression_Project4')
runfile('C:/Users/wzy/Desktop/MachineLearning/LinearRegression_Project4/LinearRegression.py', wdir='C:/Users/wzy/Desktop/MachineLearning/LinearRegression_Project4')
runfile('C:/Users/wzy/Desktop/MachineLearning/LinearRegression_Project4/LinearRegression.py', wdir='C:/Users/wzy/Desktop/MachineLearning/LinearRegression_Project4')
runfile('C:/Users/wzy/Desktop/MachineLearning/LinearRegression_Project4/LinearRegression.py', wdir='C:/Users/wzy/Desktop/MachineLearning/LinearRegression_Project4')
runfile('C:/Users/wzy/Desktop/MachineLearning/RidgeRegression_Project3/RidgeRegression.py', wdir='C:/Users/wzy/Desktop/MachineLearning/RidgeRegression_Project3')
runfile('C:/Users/wzy/Desktop/MachineLearning/RidgeRegression_Project3/RidgeRegression.py', wdir='C:/Users/wzy/Desktop/MachineLearning/RidgeRegression_Project3')
get_ipython().run_line_magic('logstart', 'cookbook_log.py rotate')
get_ipython().run_line_magic('logoff', '')
